services:

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flowly
      MYSQL_USER: flowly
      MYSQL_PASSWORD: flowly
    volumes:
      - dbdata:/var/lib/mysql

    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: database
    ports:
      - "8081:80"
    depends_on:
      - database

volumes:
  dbdata: